In [2]:
import pandas as pd

In [3]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/'
df = pd.read_csv(prefix + 'taxi_zone_lookup.csv')

In [4]:
len(df)

265

In [8]:
df.head(0)

Empty DataFrame
Columns: [LocationID, Borough, Zone, service_zone]
Index: []

In [14]:
df['tpep_pickup_datetime']

0          2021-07-01 00:08:51
1          2021-07-01 00:22:39
2          2021-07-01 00:48:33
3          2021-07-01 00:59:44
4          2021-07-01 00:08:35
                  ...
2821510    2021-07-09 18:07:09
2821511    2021-07-09 18:16:00
2821512    2021-07-09 18:07:46
2821513    2021-07-09 18:17:00
2821514    2021-07-09 18:11:00
Name: tpep_pickup_datetime, Length: 2821515, dtype: str

In [16]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    prefix + 'yellow_tripdata_2021-01.csv.gz',
    dtype=dtype,
    parse_dates=parse_dates
)

In [20]:
df['tpep_pickup_datetime']

0         2021-01-01 00:30:10
1         2021-01-01 00:51:20
2         2021-01-01 00:43:30
3         2021-01-01 00:15:48
4         2021-01-01 00:31:49
                  ...
1369760   2021-01-25 08:32:04
1369761   2021-01-25 08:34:00
1369762   2021-01-25 08:37:00
1369763   2021-01-25 08:28:00
1369764   2021-01-25 08:38:00
Name: tpep_pickup_datetime, Length: 1369765, dtype: datetime64[us]

In [9]:
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg://root:root@localhost:5432/ny_taxi')

In [10]:
df.head(0).to_sql(name='zones', con=engine, if_exists='replace')

0

In [12]:
print(pd.io.sql.get_schema(df, name='zones', con=engine))

CREATE TABLE zones (
	"LocationID" BIGINT,
	"Borough" TEXT,
	"Zone" TEXT,
	service_zone TEXT
)

In [44]:
df_iter = pd.read_csv(
    prefix + 'yellow_tripdata_2021-01.csv.gz',
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000,
)

In [45]:
from tqdm.auto import tqdm

In [46]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

0it [00:00, ?it/s]

In [38]:
df = next(df_iter)

In [39]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
100000,2,2021-01-04 14:42:51,2021-01-04 14:51:18,1,1.43,1,N,170,161,2,7.5,0.0,0.5,0.00,0.0,0.3,10.80,2.5
100001,2,2021-01-04 14:04:39,2021-01-04 14:18:41,1,2.82,1,N,170,143,2,12.0,0.0,0.5,0.00,0.0,0.3,15.30,2.5
100002,1,2021-01-04 14:12:49,2021-01-04 14:31:21,0,2.70,1,N,68,239,1,13.5,2.5,0.5,3.35,0.0,0.3,20.15,2.5
100003,1,2021-01-04 14:43:55,2021-01-04 14:48:45,1,0.70,1,N,246,68,2,5.5,2.5,0.5,0.00,0.0,0.3,8.80,2.5
100004,1,2021-01-04 14:59:16,2021-01-04 15:07:08,1,1.60,1,N,161,234,1,8.0,2.5,0.5,2.25,0.0,0.3,13.55,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,1,2021-01-06 17:02:39,2021-01-06 17:09:21,2,1.10,1,N,236,237,1,6.5,3.5,0.5,3.20,0.0,0.3,14.00,2.5
199996,1,2021-01-06 17:12:00,2021-01-06 17:17:55,1,1.60,1,N,237,239,1,7.0,3.5,0.5,2.25,0.0,0.3,13.55,2.5
199997,2,2021-01-06 17:03:41,2021-01-06 17:07:37,2,1.06,1,N,161,186,1,5.5,1.0,0.5,1.96,0.0,0.3,11.76,2.5
199998,2,2021-01-06 17:14:11,2021-01-06 17:29:58,2,5.24,1,N,68,238,1,18.0,1.0,0.5,1.00,0.0,0.3,23.30,2.5
199999,2,2021-01-06 17:45:43,2021-01-06 17:52:37,2,1.49,1,N,68,114,1,7.0,1.0,0.5,1.50,0.0,0.3,12.80,2.5